services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    networks:
      - observability-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    ports:
      - "9090:9090"
    networks:
      - observability-net

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: ["-config.file=/etc/loki/config.yml"]
    volumes:
      - ./loki/config.yml:/etc/loki/config.yml
      - loki-data:/loki
    networks:
      - observability-net

  app:
    build: ./app
    volumes:
      - ./app/contatos.xlsx:/app/contatos.xlsx
    ports:
      - "8000:8000"
    networks:
      - observability-net
    depends_on:
      - loki
      - prometheus

networks:
  observability-net:
    driver: bridge

volumes:
  loki-data:
